### ISSUE TITLE
Add missing code to identify the complete UKIT (MKIT+EKIT+WKIT+other...)

### ISSUE THREAD

**Issue by Fabrizio69** [icub-tech-iit/documentation#17]
## Task Description
The code to identify the global assembly (UKIT) to execute the upgrade is missing.

## Definition of Done
- [x] The documentation contains the upgrade identification code
- [x] Each part (MKIT, EKIT, etc) that constitutes the UKIT is described and correctly identified
- [x] The scope of the upgrade is clearly specified (for which platform)

**Comment by pattacini** [comment]
@Fabrizio69 now the documentation of UKIT should be more nice-looking from your standpoint.
Give it a glance and report here any feedback you may have, please.

**Comment by traversaro** [comment]
I am not dealing with UKIT on a daily basis, so I may suggest something that it may not have sense, but if the UKIT code is the main entry point and identified for a ukit, I think it could make sense to add it to the summary and the menu to access the UKITs: 
![summary](https://user-images.githubusercontent.com/1857049/88387150-2eb97400-cdb2-11ea-8617-b08a3357b328.PNG)

Because I imagine that in the future the number of UKITs will grow, and opening all the pages of the UKITs to understand to which human readable name corresponds the UKIT 003 may be complex.

**Comment by pattacini** [comment]
I'll do that 👍🏻

**Comment by pattacini** [comment]
Done @traversaro 👍🏻

**Comment by pattacini** [comment]
The information you required is now available @Fabrizio69.
Closing for now, you could still point us at any improvements you may have.
